Add print_address_https to ap

diff --git a/bin/environ b/bin/environ
--- a/bin/environ
+++ b/bin/environ
@@ -1,10 +1,9 @@
 #!/bin/bash
-[ ! -e environ_env ] || source environ_env
 
 usage () {
     cat <<'HELP_USAGE'
 Usage: environ [--rebuild 0] [--build 0] [--local 0] [--cachedir <0|path>] \
-               [--dir <path>] [--localdir] <product> [<path>]
+               [--dir <path>] [-l|--localdir <path>] <product> [<path>]
 
 environ - generate a folder with helper scripts to manage and automate services
   in test environments without privileged access.
@@ -24,6 +23,7 @@ environ - generate a folder with helper scripts to manage and automate services
   --cachedir <path> - use <path> for cache directory location (default is
       /temp/environ/)
   --dir <path> - path to templates (default /etc/environ.d/).
+  -l <path>,
   --localdir <path> - additional path to templates (default t/lib/environ/).
   <product> - a service for which scripts will be generated. Currently
       supported values are names of folders in --tempatedir parameter (default
@@ -171,7 +171,7 @@ case $key in
     fi
     shift # past argument
     ;;
-    --localdir)
+    -l|--localdir)
     if [[ "$2" == --* ]] || [ -z "$2" ]; then
         :
     else
@@ -212,6 +212,14 @@ rebuild=${ENVIRON_REBUILD}
 local=${ENVIRON_LOCAL}
 template=${ENVIRON_DIR}
 template_local=${ENVIRON_LOCAL_DIR}
+type=local
+[ $# -le 1 ] || {
+    type=source
+    srcdir=$2
+    [ -d "$srcdir" ] || ( echo "Last parameter must be a valid directory {$srcdir}";  exit 1 ) >&2
+    # if t/lib/environ doest exist - use it from $srcdir
+    [ ! -d "$srcdir"/t/lib/environ ] || [ -d t/lib/environ ] || template_local="$srcdir"/t/lib/environ
+}
 
 cleanup_message=0
 # try to stop existing environ, if possible
@@ -239,9 +247,6 @@ done
 [ -z "$cache" ] || [ -z "$env" ] || [ ! -L "$cache/$env" ] || rm "$cache/$env"
 # remove environ folder in current directory
 [ -z "$local" ] || [ "$local" == 0 ] || [ -z "$env" ] || [ ! -e "$env" ] || rm -rf "$env"
-
-type=local
-[ $# -le 1 ] || type=source
 
 [ -d "$template/$product/$type/" ] || [ -d $template_local/$product/$type ] ||  (
     message="Cannot find '$type' templates for {$product} in {$template}"
@@ -283,6 +288,11 @@ else
         port_base="$(cat $template_local/$product/port_base.cnf)"
         port=$((wid * 10 + port_base))
     }
+    _exec_present=0
+    # just check if _exec script present in iteration
+    for filename in {$template,$template_local}/{$product/$type}/_exec.m4 ; do
+        [ -f $filename ] || _exec_present=1
+    done
 
     for filename in {$template,$template_local}/{common,$product/$type}/* ; do
         if [ -d $filename ] ; then
@@ -293,7 +303,7 @@ else
                 dst=$workdir/$(basename $folder)/$(basename $src)
                 dst=${dst%.m4}
                 dst=${dst%.sh}
-                opts="-D__wid=$wid -D__workdir=$workdir/$(basename $folder) -D__datadir=$workdir/$(basename $folder)/dt -D__user=$USER -D__lockdir=$cache -D__environ=$env"
+                opts="-D__wid=$wid -D__workdir=$workdir/$(basename $folder) -D__datadir=$workdir/$(basename $folder)/dt -D__port=$port -D__user=$USER -D__lockdir=$cache -D__environ=$env"
                 if [ $type == source ]; then
                     opts="$opts -D__srcdir=$workdir/src -D__blddir=$workdir/bld -D__installdir=$workdir/install"
                 fi
@@ -301,9 +311,11 @@ else
                 [[ $src != *.sh.m4 ]] || chmod +x "$dst"
             done
         else
+            # we skip generating start/stop/status from common, unless _exec preset
+            [[ ! $filename =~ .*/common/(start|stop|status).sh.m4 ]] || [ "$_exec_present" == 1 ] || continue
             opts="-D__wid=$wid -D__workdir=$workdir -D__datadir=$workdir/dt -D__port=$port -D__user=$USER -D__lockdir=$cache -D__environ=$env"
             if [ $type == source ]; then
-                ln -sfn $2 $workdir/src
+                ln -sfn $srcdir $workdir/src
                 opts="$opts -D__srcdir=$workdir/src -D__blddir=$workdir/bld -D__installdir=$workdir/install"
             fi
             [ -f "$filename" ] || continue
@@ -315,6 +327,45 @@ else
             [[ $filename != *.sh.m4 ]] || chmod +x "$dest"
         fi
     done
+    services=""
+    if [ -f "$template_local/$product/$type"/.service.lst  ]; then
+        services="$template_local/$product/$type"/.service.lst
+        servicedir="$template_local/$product/$type"/.service
+    elif [ -f "$template/$product/$type"/.service.lst  ]; then
+        services="$template/$product/$type"/.service.lst
+        servicedir="$template/$product/$type"/.service
+    fi
+    if [ -n "$services" ]; then
+        # generate start / stop scripts by just calling the same operation for every service
+        echo 'set -e'   > $workdir/start
+        echo failures=0 > $workdir/status
+        echo failures=0 > $workdir/stop
+        for service in $(cat "$services") ; do
+            mkdir -p "$workdir/$service"
+            for src in $servicedir/*.m4 ; do
+                [ -f "$src" ] || contunue
+                dst=$workdir/${service}/$(basename $src)
+                dst=${dst%.m4}
+                dst=${dst%.sh}
+                opts="-D__wid=$wid -D__workdir=$workdir -D__datadir=$workdir/dt -D__port=$port -D__user=$USER -D__lockdir=$cache -D__environ=$env"
+                if [ $type == source ]; then
+                    opts="$opts -D__srcdir=$workdir/src -D__blddir=$workdir/bld -D__installdir=$workdir/install"
+                fi
+                m4 $opts -D__service=$service $src > $dst
+                [[ $src != *.sh.m4 ]] || chmod +x "$dst"
+            done
+            [[ $service =~ worker ]] || {
+                echo $workdir/$service/start >> $workdir/start
+                echo "$workdir/$service/status || : \$((failures++))" >> $workdir/status
+                echo "$workdir/$service/stop   || : \$((failures++))" >> $workdir/stop
+            }
+        done
+        echo '( exit $failures )' >> $workdir/status
+        echo '( exit $failures )' >> $workdir/stop
+        chmod +x $workdir/start
+        chmod +x $workdir/status
+        chmod +x $workdir/stop
+    fi
 fi
 
 [ -z "$ENVIRON_BUILD" ] || [ 0 == "$ENVIRON_BUILD" ] || {
